import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MOA",
  description: "Generated by Israel Rios",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col justify-center items-center  font-poppins">
          <div>
            <Header />
            <Suspense fallback={<div>Cargando...</div>}>
              <section className="flex flex-col  items-center ">
                {children}
              </section>
            </Suspense>
            <Footer />
          </div>
        </main>
      </body>
    </html>
  );
}
